### ISSUE TITLE
Add retworkx to Zenodo

### ISSUE THREAD

**Issue by IvanIsCoding** [Qiskit/retworkx#481]
### What is the expected enhancement?

Add retworkx to https://zenodo.org/. We will be eventually asked for a DOI for retworkx's code in our JOSS submission, and Zenodo is one of the easiest ways to do that.

Also, this would make retworkx consistent with other packages such as [qiskit-terra](https://doi.org/10.5281/zenodo.5535809
) that have a DOI and are on Zenodo.

**Comment by IvanIsCoding** [comment]
Pinging @cbjuan to ask about https://zenodo.org/communities/qiskit/?page=1&size=20 and the other packages in Zenodo

**Comment by cbjuan** [comment]
Hi @IvanIsCoding. I can definitely help with that, I can submit a retworkx record to Zenodo's Qiskit community. I would need some stuff to create the record the first time (the next retworkx releases will create a new record automatically). Some things I need:

- A title
- A list of authors

If you want we can work to enable it via this issue or we can schedule a meeting to define everything needed and create the first record.

**Comment by IvanIsCoding** [comment]
> Hi @IvanIsCoding. I can definitely help with that, I can submit a retworkx record to Zenodo's Qiskit community. I would need some stuff to create the record the first time (the next retworkx releases will create a new record automatically). Some things I need:
> 
> * A title
> * A list of authors
> 
> If you want we can work to enable it via this issue or we can schedule a meeting to define everything needed and create the first record.

@cbjuan, thanks for the quick response. I think we can work to create the first record through this issue. 

The title will be retworkx and I listed the authors below with their ORCIDs:

```yaml
title: 'retworkx'
authors:
  - name: Matthew Treinish
    orcid: 0000-0001-9713-2875
  - name: Ivan Carvalho
    orcid: 0000-0002-8257-2103
  - name: Georgios Tsilimigkounakis
    orcid: 0000-0001-6174-0801
  - name: Nahum Sá
    orcid: 0000-0002-3234-8154
```
